# Generated by Django 4.2 on 2023-04-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variations',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variations',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variations',
            name='size',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Variations',
        ),
    ]
