# Generated by Django 4.2 on 2023-04-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_wishlistitem_product_remove_wishlistitem_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='price_multiplier',
        ),
    ]
