# Generated by Django 4.2 on 2023-04-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_banners_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, upload_to='photos/banner')),
                ('is_selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Banners',
        ),
    ]
